[package]
name = "riolog"
version = "1.1.1"
authors = ["Michał Małek <michalm@fastmail.fm>"]
edition = "2018"

[dependencies]
chrono = '0.4.10'
clap = '^2.32'
subslice = '0.2.2'
streaming-iterator = { version = '0.1.5', features = ["std"] }
