name: Rust

on: [push]

jobs:
  build-unix:
    name: Build on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04 ubuntu-16.04 macos-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: riolog-${{ matrix.os }}
        path: target/release/riolog

  build-windows:
    name: Build on windows-latest

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --release --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: riolog-windows-latest
        path: target/release/riolog.exe
